import { test } from '@playwright/test';
import { ProfileParams } from '../../config/TestData.js';
import { JobPage } from '../../pages/JobPage.js';
test.describe('TEST SUITE TORQ FX -> LOGIN CREATE NEW JOB', () => {
    let jobpage;
    test.beforeEach(async ({ page }) => {
        jobpage = new JobPage(page);
        await page.goto('#/dashboardMain');
        await jobpage.TORQJobListPage();
        await jobpage.NewJobAddSource();
    });

    test.afterEach(async ({ page }) => {
        await jobpage.TORQSUBMENUFromJob();
        await page.reload()
        await page.waitForTimeout(2000);
        if (await jobpage.Stopvalidation.count() > 0) {
            await jobpage.clickAllStops();
        }
    });

    test.setTimeout(70000);
    test('PROFILE PARAMETER-TORQ-FX| TC-> 1 | UDP | ENCODE VIDEO AT 144P | UDP', async ({ page }) => {
        const TestCase = 'TC1';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 2 | UDP | ENCODE VIDEO AT 240P | UDP', async ({ page }) => {
        const TestCase = 'TC2';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });

    test('PROFILE PARAMETER -TORQ-FX| TC-> 3 | UDP | ENCODE VIDEO AT 360P | UDP', async ({ page }) => {
        const TestCase = 'TC3';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 4 | UDP | ENCODE VIDEO AT 480P | UDP', async ({ page }) => {
        const TestCase = 'TC4';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 5 | UDP | ENCODE VIDEO AT 720P | UDP', async ({ page }) => {
        const TestCase = 'TC5';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 6 | UDP | ENCODE VIDEO AT 1080P | UDP', async ({ page }) => {
        const TestCase = 'TC6';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 7 | UDP | ENCODE VIDEO AT 480i | UDP', async ({ page }) => {
        const TestCase = 'TC7';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 8 | UDP | ENCODE VIDEO AT 576i | UDP', async ({ page }) => {
        const TestCase = 'TC8';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 9 | UDP | ENCODE VIDEO AT 2160p UHD | UDP', async ({ page }) => {
        const TestCase = 'TC9';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 10 | UDP | ENCODE VIDEO AT 4K DCI | UDP', async ({ page }) => {
        const TestCase = 'TC10';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);

        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 11 | UDP | ENCODE VIDEO AT Custom | UDP', async ({ page }) => {
        const TestCase = 'TC11';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.ModifyBitrateWhileAddingJob(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 12 | UDP | ENCODE TYPE HW | UDP', async ({ page }) => {
        const TestCase = 'TC12';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton(ProfileParams[TestCase]);
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 13 | UDP | ENCODE TYPE SW | UDP', async ({ page }) => {
        const TestCase = 'TC13';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton(ProfileParams[TestCase]);
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 14 | UDP | FRAME RATE CONVERTOR 23.976 FPS | UDP', async ({ page }) => {
        const TestCase = 'TC14';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 15 | UDP | FRAME RATE CONVERTOR 24 FPS | UDP', async ({ page }) => {
        const TestCase = 'TC15';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 16 | UDP | FRAME RATE CONVERTOR 25 FPS | UDP', async ({ page }) => {
        const TestCase = 'TC16';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 17 | UDP | FRAME RATE CONVERTOR 30 FPS | UDP', async ({ page }) => {
        const TestCase = 'TC17';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 18 | UDP | FRAME RATE CONVERTOR 60 FPS | UDP', async ({ page }) => {
        const TestCase = 'TC18';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 19 | UDP | FRAME RATE CONVERTOR CUSTOM FPS | UDP', async ({ page }) => {
        const TestCase = 'TC19';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 20 | UDP | SCALING TYPE - Low Complexity | UDP', async ({ page }) => {
        const TestCase = 'TC20';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 21 | UDP | SCALING TYPE - HIGH QUALITY | UDP', async ({ page }) => {
        const TestCase = 'TC21';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 22 | UDP | SCALING TYPE - Anti-Alias | UDP', async ({ page }) => {
        const TestCase = 'TC22';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 23 | UDP | SCALING TYPE - SINC | UDP', async ({ page }) => {
        const TestCase = 'TC23';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 24 | UDP | SCALING TYPE - FAST BILINEAR | UDP', async ({ page }) => {
        const TestCase = 'TC24';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 25 | UDP | SCALING TYPE - BILINEAR | UDP', async ({ page }) => {
        const TestCase = 'TC25';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 26 | UDP | SCALING TYPE - BICUBIC | UDP', async ({ page }) => {
        const TestCase = 'TC26';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 31 | UDP | DAR W*H - 4:3 | UDP', async ({ page }) => {
        const TestCase = 'TC31';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 32 | UDP | DAR W*H - 16:9 | UDP', async ({ page }) => {
        const TestCase = 'TC32';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 33 | UDP | | UDP', async ({ page }) => {
        const TestCase = 'TC33';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 42 | UDP | GOP INTERVAL - 50 | UDP', async ({ page }) => {
        const TestCase = 'TC42';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 43 | UDP | BITRATE - DEFAULT | UDP', async ({ page }) => {
        const TestCase = 'TC43';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 44 | UDP | BITRATE - DEFAULT | UDP', async ({ page }) => {
        const TestCase = 'TC44';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 45 | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC45';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 46 | UDP | RATE CONTROL MODE - VBR | UDP', async ({ page }) => {
        const TestCase = 'TC46';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 47 | UDP | RATE CONTROL MODE - CVBR | UDP', async ({ page }) => {
        const TestCase = 'TC47';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 48 | UDP | RATE CONTROL MODE - CQP | UDP', async ({ page }) => {
        const TestCase = 'TC48';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 49 | UDP | RATE CONTROL MODE - CQP | UDP', async ({ page }) => {
        const TestCase = 'TC49';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 50 | UDP | PROFILE - BASELINE | UDP', async ({ page }) => {
        const TestCase = 'TC50';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 51 | UDP | PROFILE - MAIN | UDP', async ({ page }) => {
        const TestCase = 'TC51';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 52 | UDP | PROFILE - HIGH | UDP', async ({ page }) => {
        const TestCase = 'TC52';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 53 | UDP | PROFILE - HIGH 10 | UDP', async ({ page }) => {
        const TestCase = 'TC53';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 54 | UDP | LEVEL - SYS COMPUTE | UDP', async ({ page }) => {
        const TestCase = 'TC54';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 55 | UDP | RC-ENABLE | UDP', async ({ page }) => {
        const TestCase = 'TC55';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 56 | UDP | MINI FRAMES DELAY - DISABLE | UDP', async ({ page }) => {
        const TestCase = 'TC56';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 1AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC1AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 2AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC2AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 3AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC3AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 4AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC4AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 5AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC5AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 6AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC6AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 7AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC7AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 8AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC8AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 9AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC9AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 10AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC10AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 11AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC11AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 12AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC12AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 13AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC13AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 14AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC14AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 15AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC15AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 16AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC16AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 17AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC17AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 18AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC18AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });
    test('PROFILE PARAMETER -TORQ-FX| TC-> 19AC | Audio | UDP | RATE CONTROL MODE - CBR | UDP', async ({ page }) => {
        const TestCase = 'TC19AC';
        await jobpage.JobNameDecoderScalingType(ProfileParams[TestCase]);
        await jobpage.UDPInput(ProfileParams[TestCase]);
        await jobpage.AddInputButton();
        await jobpage.AddedInputValidation();
        await jobpage.selectDropdownOption(ProfileParams[TestCase]);
        await jobpage.OutputButton();
        await jobpage.udpoutput(ProfileParams[TestCase]);
        await jobpage.AddedOutputValidation(ProfileParams[TestCase]);
        await jobpage.AddJobButton();
        await jobpage.JobcreationPopUp();
        // await validateJobStatus(jobpage, test, page);
    });




});